# This file was generated by GoReleaser. DO NOT EDIT.
cask "replicant" do
  module GitHubHelper
    def self.token
      require "utils/github"

      github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
      github_token ||= GitHub::API.credentials
      raise "Failed to retrieve GitHub API token" if github_token.nil? || github_token.empty?

      github_token
    end

    def self.release_asset_url(tag, name)
      require "json"
      require "net/http"
      require "uri"

      uri = URI.parse("https://api.github.com/repos/DavidPerezP124/homebrew-replicant/releases/tags/#{tag}")
      response = Net::HTTP.start(uri.host, uri.port, use_ssl: true) do |http|
        request = Net::HTTP::Get.new(uri)
        request["Accept"] = "application/vnd.github+json"
        request["Authorization"] = "Bearer #{token}"
        request["X-GitHub-Api-Version"] = "2022-11-28"
        http.request(request)
      end

      raise "Failed to look up release #{tag}: #{response.code} #{response.message}" unless response.is_a?(Net::HTTPSuccess)

      release = JSON.parse(response.body)
      asset = release.fetch("assets").find { |candidate| candidate["name"] == name }
      raise "Failed to find release asset #{name} for #{tag}" if asset.nil?

      asset.fetch("url")
    end
  end

  version "0.0.1"

  on_macos do
    on_intel do
      url "#{GitHubHelper.release_asset_url("#{version}", "replicant_Darwin_x86_64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "be8d78d008888098215725ec20405de70e8754efdbeec864d92b7161a0b8afc5"
    end
    on_arm do
      url "#{GitHubHelper.release_asset_url("#{version}", "replicant_Darwin_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "48e5f1ffb4d8d82cce6bb9e657679d72baf1a3d46db2a45fd473b4083f1b2383"
    end
  end

  on_linux do
    on_intel do
      url "#{GitHubHelper.release_asset_url("#{version}", "replicant_Linux_x86_64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "a41bb61a3e7b07549a182dd4170de95b97151c28d048f721cc8faec2cb8d13e1"
    end
    on_arm do
      url "#{GitHubHelper.release_asset_url("#{version}", "replicant_Linux_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "215150ff288a134707ed13afa1f76acbfbd1565fae1ad1855ab25c85d9ddc5c3"
    end
  end

  name "replicant"
  desc "TUI for proxying and matching requests to edited responses"
  homepage "https://github.com/DavidPerezP124/homebrew-replicant"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "replicant"

  # No zap stanza required

  caveats <<~EOS
    Export `HOMEBREW_GITHUB_API_TOKEN` with access to the private source repo
    before installing from this tap.
  EOS
end
