# This file was generated by GoReleaser. DO NOT EDIT.
cask "replicant" do
  module Utils
    class << self
      require "utils/github"

      define_method(:github_helper_token) do
        github_token = ENV.fetch("GITHUB_TOKEN", nil)
        github_token ||= GitHub::API.credentials

        raise "Failed to retrieve GitHub API token" if github_token.blank?

        github_token
      end

      define_method(:github_release_asset_url) do |tag, name|
        require "json"
        require "net/http"
        require "uri"

        uri = URI.parse("https://api.github.com/repos/DavidPerezP124/replicant/releases/tags/#{tag}")
        response = Net::HTTP.start(uri.host, uri.port, use_ssl: true) do |http|
          request = Net::HTTP::Get.new(uri)
          request["Accept"] = "application/vnd.github+json"
          request["Authorization"] = "Bearer #{github_helper_token}"
          request["X-GitHub-Api-Version"] = "2022-11-28"
          http.request(request)
        end

        unless response.is_a?(Net::HTTPSuccess)
          raise "Failed to look up release #{tag}: #{response.code} #{response.message}"
        end

        release = JSON.parse(response.body)
        asset = release.fetch("assets").find { |candidate| candidate["name"] == name }
        raise "Failed to find release asset #{name} for #{tag}" if asset.nil?

        asset.fetch("url")
      end
    end
  end

  version "0.0.4"

  on_macos do
    on_intel do
      url "#{Utils.github_release_asset_url(version.to_s, "replicant_Darwin_x86_64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{Utils.github_helper_token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "323efef1ae2c27c4e9c5875166dfcc68da28fdacfcc53f582c74bb5a81de84dd"
    end
    on_arm do
      url "#{Utils.github_release_asset_url(version.to_s, "replicant_Darwin_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{Utils.github_helper_token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "5578e2065bd603c1dfe8d4b8f2cf7979dda448095a9b5997a1794bf4ccc92670"
    end
  end

  on_linux do
    on_intel do
      url "#{Utils.github_release_asset_url(version.to_s, "replicant_Linux_x86_64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{Utils.github_helper_token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "967daa17b0f17a799824e9473370031461a03f44fd6ff2ad274f9fb65ce3437f"
    end
    on_arm do
      url "#{Utils.github_release_asset_url(version.to_s, "replicant_Linux_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{Utils.github_helper_token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "e95f16e47225c7697d4e4360596eadabdf654c72bb5a16d8d85d4f0e73affeb8"
    end
  end

  name "replicant"
  desc "TUI for proxying and matching requests to edited responses"
  homepage "https://github.com/DavidPerezP124/homebrew-replicant"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "replicant"

  # No zap stanza required

  caveats <<~EOS
    Export `HOMEBREW_GITHUB_API_TOKEN` with access to the private source repo
    before installing from this tap.
  EOS
end
