# This file was generated by GoReleaser. DO NOT EDIT.
cask "replicant" do
  module Utils
    class << self
      require "utils/github"

      define_method(:github_helper_token) do
        github_token = ENV.fetch("GITHUB_TOKEN", nil)
        github_token ||= GitHub::API.credentials

        raise "Failed to retrieve GitHub API token" if github_token.blank?

        github_token
      end

      define_method(:github_release_asset_url) do |tag, name|
        require "json"
        require "net/http"
        require "uri"

        uri = URI.parse("https://api.github.com/repos/DavidPerezP124/replicant/releases/tags/#{tag}")
        response = Net::HTTP.start(uri.host, uri.port, use_ssl: true) do |http|
          request = Net::HTTP::Get.new(uri)
          request["Accept"] = "application/vnd.github+json"
          request["Authorization"] = "Bearer #{github_helper_token}"
          request["X-GitHub-Api-Version"] = "2022-11-28"
          http.request(request)
        end

        unless response.is_a?(Net::HTTPSuccess)
          raise "Failed to look up release #{tag}: #{response.code} #{response.message}"
        end

        release = JSON.parse(response.body)
        asset = release.fetch("assets").find { |candidate| candidate["name"] == name }
        raise "Failed to find release asset #{name} for #{tag}" if asset.nil?

        asset.fetch("url")
      end
    end
  end

  version "0.0.2"

  on_macos do
    on_intel do
      url "#{Utils.github_release_asset_url(version.to_s, "replicant_Darwin_x86_64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{Utils.github_helper_token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "cae9dd8262082a52118e4ac6bd9a22521f18306607ffdc1152074b2a39d74835"
    end
    on_arm do
      url "#{Utils.github_release_asset_url(version.to_s, "replicant_Darwin_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{Utils.github_helper_token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "8cd94f8a14baf4f9fcdefd7d1b2648b52aaa61437479284ba584e90ceffa9d49"
    end
  end

  on_linux do
    on_intel do
      url "#{Utils.github_release_asset_url(version.to_s, "replicant_Linux_x86_64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{Utils.github_helper_token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "e5104303d10b628c91069459f88c6a51d5abfb940e2da61c0396550192a866ea"
    end
    on_arm do
      url "#{Utils.github_release_asset_url(version.to_s, "replicant_Linux_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{Utils.github_helper_token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "1a78c7f3f8f9f90c7d559b237ec0a118bfccbfcd2aa01aff4a47e975af1ff157"
    end
  end

  name "replicant"
  desc "TUI for proxying and matching requests to edited responses"
  homepage "https://github.com/DavidPerezP124/homebrew-replicant"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "replicant"

  # No zap stanza required

  caveats <<~EOS
    Export `HOMEBREW_GITHUB_API_TOKEN` with access to the private source repo
    before installing from this tap.
  EOS
end
